package com.tywho.dblibrary.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tywho.dblibrary.bean.AppStartImage;
import com.tywho.dblibrary.bean.CookieResulte;

import com.tywho.dblibrary.dao.AppStartImageDao;
import com.tywho.dblibrary.dao.CookieResulteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appStartImageDaoConfig;
    private final DaoConfig cookieResulteDaoConfig;

    private final AppStartImageDao appStartImageDao;
    private final CookieResulteDao cookieResulteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appStartImageDaoConfig = daoConfigMap.get(AppStartImageDao.class).clone();
        appStartImageDaoConfig.initIdentityScope(type);

        cookieResulteDaoConfig = daoConfigMap.get(CookieResulteDao.class).clone();
        cookieResulteDaoConfig.initIdentityScope(type);

        appStartImageDao = new AppStartImageDao(appStartImageDaoConfig, this);
        cookieResulteDao = new CookieResulteDao(cookieResulteDaoConfig, this);

        registerDao(AppStartImage.class, appStartImageDao);
        registerDao(CookieResulte.class, cookieResulteDao);
    }
    
    public void clear() {
        appStartImageDaoConfig.clearIdentityScope();
        cookieResulteDaoConfig.clearIdentityScope();
    }

    public AppStartImageDao getAppStartImageDao() {
        return appStartImageDao;
    }

    public CookieResulteDao getCookieResulteDao() {
        return cookieResulteDao;
    }

}
